<?php
/**
 * CSV Exporter streams all posts of a given post type as a downloadable CSV.
 *
 * @package Post_Type_Transfer
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'PTT_CSV_Exporter' ) ) {

	/**
	 * Handles the admin_post_ptt_export_csv action.
	 *
	 * Fixed columns:
	 *   ID, post_title, post_content, post_name, post_status, post_date,
	 *   categories (pipe-separated), tags (pipe-separated), featured_image (URL)
	 *
	 * Dynamic meta columns:
	 *   Every distinct meta key stored against this post type is appended as
	 *   its own column.  ACF field values and ACF field-key references are both
	 *   included so a round-trip import restores full ACF state.  Array/object
	 *   values are JSON-encoded with a "__json__:" prefix.
	 *
	 * Developer filters (see inline apply_filters() calls for full signatures):
	 *   ptt_csv_export_filename — the downloaded file name
	 *   ptt_csv_export_columns  — ordered list of column names
	 *   ptt_csv_export_row      — associative row data per post
	 */
	class PTT_CSV_Exporter {

		/**
		 * Meta keys generated by WordPress core that carry no meaning outside
		 * their original environment and should not be exported.
		 *
		 * @var string[]
		 */
		private static $excluded_meta_keys = array(
			'_edit_lock',             // Transient write-lock — meaningless after export.
			'_edit_last',             // User ID of last editor — not valid on another site.
			'_thumbnail_id',          // Handled via the dedicated featured_image column.
			'_encloseme',             // Internal podcast-enclosure queue flag.
			'_pingme',                // Internal ping-queue flag.
			'_wp_trash_meta_status',  // Trash metadata.
			'_wp_trash_meta_time',    // Trash metadata.
			'_wp_desired_post_slug',  // Transient slug-resolution hint.
			'_wp_old_slug',           // Historical slug — would confuse import matching.
			'_wp_old_date',           // Historical date archive redirect.
		);

		/**
		 * Register hooks.
		 */
		public function __construct() {
			add_action( 'admin_post_ptt_export_csv', array( $this, 'handle_export' ) );
		}

		/**
		 * Entry point for the export action.
		 */
		public function handle_export() {
			$post_type = isset( $_GET['post_type'] ) ? sanitize_key( wp_unslash( $_GET['post_type'] ) ) : '';

			if ( ! $post_type ) {
				wp_die( esc_html__( 'Invalid post type.', 'post-type-transfer' ) );
			}

			if (
				! isset( $_GET['ptt_nonce'] ) ||
				! wp_verify_nonce(
					sanitize_text_field( wp_unslash( $_GET['ptt_nonce'] ) ),
					'ptt_export_csv_' . $post_type
				)
			) {
				wp_die( esc_html__( 'Security check failed.', 'post-type-transfer' ) );
			}

			$obj = get_post_type_object( $post_type );
			if ( ! $obj || ! current_user_can( $obj->cap->edit_posts ) ) {
				wp_die( esc_html__( 'You do not have permission to export these posts.', 'post-type-transfer' ) );
			}

			$excluded = apply_filters(
				'ptt_csv_excluded_post_types',
				array( 'product', 'product_variation', 'shop_order', 'shop_coupon', 'shop_webhook' )
			);
			if ( in_array( $post_type, (array) $excluded, true ) ) {
				wp_die( esc_html__( 'CSV export is not available for this post type.', 'post-type-transfer' ) );
			}

			$posts     = $this->get_all_posts( $post_type );
			$meta_keys = $this->get_meta_keys( $post_type );

			$this->stream_csv( $post_type, $posts, $meta_keys );
		}

		/**
		 * Retrieve all posts of a given type.
		 *
		 * @param string $post_type Post type slug.
		 * @return WP_Post[]
		 */
		private function get_all_posts( $post_type ) {
			return get_posts(
				array(
					'post_type'      => $post_type,
					'post_status'    => array( 'publish', 'draft', 'private', 'pending', 'future' ),
					'posts_per_page' => -1,
					'orderby'        => 'ID',
					'order'          => 'ASC',
					'no_found_rows'  => true,
				)
			);
		}

		/**
		 * Return all distinct meta keys used by this post type, sorted alphabetically,
		 * with WP-internal keys removed.
		 *
		 * @param string $post_type Post type slug.
		 * @return string[]
		 */
		private function get_meta_keys( $post_type ) {
			global $wpdb;

			// phpcs:ignore WordPress.DB.DirectDatabaseQuery
			$keys = $wpdb->get_col(
				$wpdb->prepare(
					"SELECT DISTINCT pm.meta_key
					 FROM {$wpdb->postmeta} AS pm
					 INNER JOIN {$wpdb->posts} AS p ON p.ID = pm.post_id
					 WHERE p.post_type   = %s
					 AND   p.post_status IN ('publish','draft','private','pending','future')
					 ORDER BY pm.meta_key ASC",
					$post_type
				)
			);

			if ( ! $keys ) {
				return array();
			}

			return array_values( array_diff( $keys, self::$excluded_meta_keys ) );
		}

		/**
		 * Output CSV headers and rows, then exit.
		 *
		 * @param string    $post_type Post type slug (used in the filename).
		 * @param WP_Post[] $posts     Posts to export.
		 * @param string[]  $meta_keys Sorted list of meta keys to include as extra columns.
		 */
		private function stream_csv( $post_type, $posts, $meta_keys ) {
			$default_filename = sanitize_file_name( $post_type . '-export-' . gmdate( 'Y-m-d' ) . '.csv' );

			/**
			 * Filter the filename of the exported CSV download.
			 *
			 * @param string $filename  Default filename (e.g. "post-export-2025-01-01.csv").
			 * @param string $post_type Post type slug.
			 */
			$filename = (string) apply_filters( 'ptt_csv_export_filename', $default_filename, $post_type );

			/**
			 * Filter the ordered list of column names written as the CSV header row.
			 *
			 * Each string in the array is both the header label in the CSV file and the
			 * array key used in the ptt_csv_export_row filter.  Add a custom column here
			 * and populate its value via ptt_csv_export_row.
			 *
			 * @param string[] $columns   Default columns (fixed structural + all meta keys).
			 * @param string   $post_type Post type slug.
			 */
			$columns = (array) apply_filters(
				'ptt_csv_export_columns',
				array_merge(
					array( 'ID', 'post_title', 'post_content', 'post_name', 'post_status', 'post_date', 'categories', 'tags', 'featured_image' ),
					$meta_keys
				),
				$post_type
			);

			// Discard ALL active output buffer levels so headers arrive clean.
			while ( ob_get_level() ) {
				ob_end_clean();
			}

			header( 'Content-Type: text/csv; charset=utf-8' );
			header( 'Content-Disposition: attachment; filename="' . $filename . '"' );
			header( 'Pragma: no-cache' );
			header( 'Expires: 0' );

			$out = fopen( 'php://output', 'w' ); // phpcs:ignore WordPress.WP.AlternativeFunctions

			// UTF-8 BOM — improves Excel compatibility without breaking other tools.
			fwrite( $out, "\xEF\xBB\xBF" ); // phpcs:ignore WordPress.WP.AlternativeFunctions

			fputcsv( $out, $columns );

			foreach ( $posts as $post ) {
				// Build row as an associative array keyed by column name so the
				// ptt_csv_export_row filter can reference fields by name, not position.
				$row = array(
					'ID'             => $post->ID,
					'post_title'     => $post->post_title,
					'post_content'   => $post->post_content,
					'post_name'      => $post->post_name,
					'post_status'    => $post->post_status,
					'post_date'      => $post->post_date,
					'categories'     => $this->get_term_names( $post->ID, 'category' ),
					'tags'           => $this->get_term_names( $post->ID, 'post_tag' ),
					'featured_image' => $this->get_featured_image_url( $post->ID ),
				);

				foreach ( $meta_keys as $key ) {
					$row[ $key ] = $this->encode_meta_value( get_post_meta( $post->ID, $key, true ) );
				}

				/**
				 * Filter an individual post's row data before it is written to the CSV.
				 *
				 * The array is keyed by column name (matching the ptt_csv_export_columns
				 * list).  Add values for any extra columns added via ptt_csv_export_columns,
				 * or modify/remove existing ones.  Missing keys default to an empty string.
				 *
				 * @param array<string,mixed> $row       Associative column => value map.
				 * @param WP_Post             $post      Current post object.
				 * @param string              $post_type Post type slug.
				 */
				$row = (array) apply_filters( 'ptt_csv_export_row', $row, $post, $post_type );

				// Extract values in the exact column order so they align with headers.
				$values = array();
				foreach ( $columns as $col ) {
					$values[] = isset( $row[ $col ] ) ? $row[ $col ] : '';
				}

				fputcsv( $out, $values );
			}

			fclose( $out ); // phpcs:ignore WordPress.WP.AlternativeFunctions
			exit;
		}

		/**
		 * Return pipe-separated term names for a post/taxonomy pair.
		 *
		 * @param int    $post_id  Post ID.
		 * @param string $taxonomy Taxonomy slug.
		 * @return string
		 */
		private function get_term_names( $post_id, $taxonomy ) {
			$terms = get_the_terms( $post_id, $taxonomy );
			if ( ! $terms || is_wp_error( $terms ) ) {
				return '';
			}
			return implode( '|', wp_list_pluck( $terms, 'name' ) );
		}

		/**
		 * Return the full URL of the post's featured image, or empty string.
		 *
		 * @param int $post_id Post ID.
		 * @return string
		 */
		private function get_featured_image_url( $post_id ) {
			$thumb_id = get_post_thumbnail_id( $post_id );
			if ( ! $thumb_id ) {
				return '';
			}
			$url = wp_get_attachment_url( $thumb_id );
			return $url ? (string) $url : '';
		}

		/**
		 * Encode a meta value for safe storage in a CSV cell.
		 *
		 * Scalar values are cast to string unchanged.  Arrays and objects are
		 * JSON-encoded and prefixed with "__json__:" so the importer can restore
		 * them exactly.  Falls back to "__serialized__:" when JSON encoding fails.
		 *
		 * @param mixed $value Raw value from get_post_meta().
		 * @return string
		 */
		private function encode_meta_value( $value ) {
			if ( is_array( $value ) || is_object( $value ) ) {
				$encoded = wp_json_encode( $value );
				if ( false === $encoded ) {
					return '__serialized__:' . serialize( $value ); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize
				}
				return '__json__:' . $encoded;
			}
			return (string) $value;
		}
	}
}
